const fs = require('fs');

const code = `import { Product } from '../types';

export const PRODUCTS: Product[] = [
  {
    id: 'senka-perfect-whip-collagen',
    title: 'Senka Perfect Whip Collagen-In',
    subtitle: 'Beauty Foam with Collagen GL',
    price: 750,
    originalPrice: 950,
    rating: 4.8,
    reviewsCount: 312,
    category: 'Face Wash',
    skinTypes: ['Dry', 'Mature', 'Normal'],
    skinConcerns: ['Anti-Aging', 'Hydration'],
    routine: 'AM/PM',
    volume: '120g',
    badges: ['Bestseller', 'Collagen'],
    image: 'https://m.media-amazon.com/images/I/41Dq786fHzL._SX300_SY300_QL70_FMwebp_.jpg',
    accentColor: '#f472b6',
    bgGradient: 'from-pink-50 to-pink-100',
    keyActives: [
      { name: 'Collagen GL', purpose: 'Improves skin elasticity' },
      { name: 'Silk Essence', purpose: 'Protects skin barrier' },
      { name: 'Double Hyaluronic Acid', purpose: 'Deep hydration' }
    ],
    fullIngredients: 'Water, Stearic Acid, PEG-8, Myristic Acid, Potassium Hydroxide, Glycerin, Lauric Acid, Alcohol, Soluble Collagen...',
    description: 'A rich, micro-dense foaming cleanser enriched with beauty serum and collagen to gently cleanse while leaving skin plump and hydrated.',
    benefits: ['Plumps skin', 'Removes impurities without stripping moisture', 'Rich micro-lather'],
    usageHowTo: 'Take an appropriate amount (about 2cm) onto your palms, add a small amount of water to work up a good lather, and wash gently.',
    isBestSeller: true,
    stock: 50
  },
  {
    id: 'vitamin-c-capsule-serum',
    title: 'Premium Vitamin C Capsule Serum',
    subtitle: 'Enriched by Fresh Capsules',
    price: 1850,
    originalPrice: 2200,
    rating: 4.9,
    reviewsCount: 156,
    category: 'Serum',
    skinTypes: ['All', 'Combination', 'Oily'],
    skinConcerns: ['Glow & Dullness', 'Blemishes & Texture'],
    routine: 'AM/PM',
    volume: '30ml',
    badges: ['New', 'Brightening'],
    image: 'https://m.media-amazon.com/images/I/41o+27w3FHL._SX300_SY300_QL70_FMwebp_.jpg',
    accentColor: '#fbbf24',
    bgGradient: 'from-amber-50 to-amber-100',
    keyActives: [
      { name: 'Pure Vitamin C', percentage: '10%', purpose: 'Brightens and evens skin tone' },
      { name: 'Fresh Capsules', purpose: 'Preserves active ingredients' }
    ],
    fullIngredients: 'Water, Ascorbic Acid (Vitamin C), Glycerin, Butylene Glycol, Dipropylene Glycol, Sodium Hyaluronate...',
    description: 'An advanced brightening serum featuring freshly sealed Vitamin C capsules that burst upon application for maximum potency.',
    benefits: ['Fades dark spots', 'Boosts radiance', 'Antioxidant protection'],
    usageHowTo: 'Apply 2-3 drops onto clean skin before moisturizer. Gently massage until capsules dissolve.',
    isNew: true,
    stock: 30
  },
  {
    id: 'keana-rice-mask',
    title: 'Keana Nadeshiko Rice Mask',
    subtitle: '10th Anniversary Edition - 100% Japanese Rice',
    price: 850,
    originalPrice: 1000,
    rating: 4.9,
    reviewsCount: 890,
    category: 'Face Mask',
    skinTypes: ['Dry', 'Normal', 'Sensitive'],
    skinConcerns: ['Hydration', 'Blemishes & Texture'],
    routine: 'PM',
    volume: '10 Sheets',
    badges: ['Award Winner', 'Pore Care'],
    image: 'https://m.media-amazon.com/images/I/51wQWqDkEKL._SX300_SY300_QL70_FMwebp_.jpg',
    accentColor: '#60a5fa',
    bgGradient: 'from-blue-50 to-blue-100',
    keyActives: [
      { name: 'Rice Serum', purpose: 'Minimizes pores and hydrates' },
      { name: 'Rice Bran Oil', purpose: 'Improves skin elasticity' }
    ],
    fullIngredients: 'Water, Glycerin, Propylene Glycol, Alcohol, Styrene/VP Copolymer, Rice Ferment Filtrate (Sake)...',
    description: 'Thick sheet masks soaked in 100% Japanese domestic rice-derived serum. Specifically formulated to hydrate dry skin and minimize the appearance of enlarged pores.',
    benefits: ['Tightens pores', 'Deeply hydrates', 'Leaves skin soft and bouncy'],
    usageHowTo: 'Apply after cleansing. Leave on for 5 minutes. Gently massage remaining essence into the skin.',
    isBestSeller: true,
    stock: 120
  },
  {
    id: 'lululun-precious-clear',
    title: 'LuLuLun Precious CLEAR',
    subtitle: 'Daily Anti-Aging Mask for Clarity',
    price: 750,
    originalPrice: 850,
    rating: 4.7,
    reviewsCount: 420,
    category: 'Face Mask',
    skinTypes: ['All', 'Mature'],
    skinConcerns: ['Anti-Aging', 'Glow & Dullness'],
    routine: 'AM/PM',
    volume: '7 Sheets',
    badges: ['Daily Use'],
    image: 'https://m.media-amazon.com/images/I/41c-D1Nn8bL._SX300_SY300_QL70_FMwebp_.jpg',
    accentColor: '#d1d5db',
    bgGradient: 'from-gray-50 to-gray-100',
    keyActives: [
      { name: 'L22 Lipid Complex', purpose: 'Replicates healthy 22-year-old sebum balance' },
      { name: 'White Mushroom Extract', purpose: 'Improves skin clarity' }
    ],
    fullIngredients: 'Water, Glycerin, Butylene Glycol, PEG-40 Hydrogenated Castor Oil, Xanthan Gum, Tetrasodium EDTA...',
    description: 'A 7-day daily mask pack designed for mature skin. Formulated to clarify, brighten, and refine skin texture.',
    benefits: ['Evens skin tone', 'Improves clarity', 'Hydrates deeply'],
    usageHowTo: 'Replace your daily toner with this mask. Apply for 5-10 minutes, then fold and pat the remaining essence.',
    stock: 45
  },
  {
    id: 'lululun-precious-moist',
    title: 'LuLuLun Precious MOIST',
    subtitle: 'Daily Anti-Aging Mask for Deep Moisture',
    price: 750,
    originalPrice: 850,
    rating: 4.8,
    reviewsCount: 510,
    category: 'Face Mask',
    skinTypes: ['Dry', 'Mature'],
    skinConcerns: ['Anti-Aging', 'Hydration'],
    routine: 'AM/PM',
    volume: '7 Sheets',
    badges: ['Intense Hydration'],
    image: 'https://m.media-amazon.com/images/I/41-q0f0i0VL._SX300_SY300_QL70_FMwebp_.jpg',
    accentColor: '#ef4444',
    bgGradient: 'from-red-50 to-red-100',
    keyActives: [
      { name: 'L22 Lipid Complex', purpose: 'Restores youth-like moisture balance' },
      { name: 'Rice Bran Extract', purpose: 'Softens and nourishes' }
    ],
    fullIngredients: 'Water, Glycerin, Butylene Glycol, PEG-40 Hydrogenated Castor Oil, Xanthan Gum, Citric Acid...',
    description: 'Ultra-moisturizing daily sheet mask specifically formulated for mature, dry skin that is losing its natural moisture retention.',
    benefits: ['Intensely moisturizes', 'Softens rough skin', 'Reduces fine lines from dryness'],
    usageHowTo: 'Apply to clean skin for 5-10 minutes daily in place of toner.',
    stock: 60
  },
  {
    id: 'lululun-precious-balance',
    title: 'LuLuLun Precious BALANCE',
    subtitle: 'Daily Anti-Aging Mask for Stability',
    price: 750,
    originalPrice: 850,
    rating: 4.8,
    reviewsCount: 380,
    category: 'Face Mask',
    skinTypes: ['Combination', 'Mature'],
    skinConcerns: ['Anti-Aging', 'Barrier Repair'],
    routine: 'AM/PM',
    volume: '7 Sheets',
    badges: ['Bestseller'],
    image: 'https://m.media-amazon.com/images/I/41f+o+4h+OL._SX300_SY300_QL70_FMwebp_.jpg',
    accentColor: '#10b981',
    bgGradient: 'from-emerald-50 to-emerald-100',
    keyActives: [
      { name: 'L22 Lipid Complex', purpose: 'Restores sebum balance' },
      { name: 'Fermented Yeast Extract', purpose: 'Strengthens skin barrier' }
    ],
    fullIngredients: 'Water, Glycerin, Butylene Glycol, PEG-40 Hydrogenated Castor Oil, Saccharomyces Ferment Filtrate...',
    description: 'The green Balance edition stabilizes fluctuating mature skin, restoring its natural elasticity and healthy barrier.',
    benefits: ['Balances oil and moisture', 'Strengthens skin barrier', 'Boosts elasticity'],
    usageHowTo: 'Apply to clean skin for 5-10 minutes daily in place of toner.',
    isBestSeller: true,
    stock: 85
  },
  {
    id: 'derma-laser-retinol',
    title: 'Quality 1st Derma Laser Super Retinol 100',
    subtitle: 'Intense Night Repair Mask',
    price: 950,
    originalPrice: 1100,
    rating: 4.9,
    reviewsCount: 650,
    category: 'Face Mask',
    skinTypes: ['All', 'Mature'],
    skinConcerns: ['Anti-Aging', 'Glow & Dullness'],
    routine: 'PM',
    volume: '7 Sheets',
    badges: ['Night Care', 'Retinol'],
    image: 'https://m.media-amazon.com/images/I/41yXG16+e-L._SX300_SY300_QL70_FMwebp_.jpg',
    accentColor: '#dc2626',
    bgGradient: 'from-red-50 to-red-100',
    keyActives: [
      { name: 'Retinol', purpose: 'Boosts cell turnover' },
      { name: 'Niacinamide', purpose: 'Brightens and supports barrier' }
    ],
    fullIngredients: 'Water, Dipropylene Glycol, Glycerin, Niacinamide, Retinol, Ceramide NP...',
    description: 'A highly concentrated night mask featuring encapsulated retinol for deep penetration, targeting fine lines, wrinkles, and signs of aging while you sleep.',
    benefits: ['Reduces fine lines', 'Firms skin', 'Improves elasticity'],
    usageHowTo: 'Use at night. Leave on for 3 minutes for quick care, or up to 10 minutes for intensive repair.',
    isBestSeller: true,
    stock: 40
  },
  {
    id: 'derma-laser-glutathione',
    title: 'Quality 1st Derma Laser Super Glutathione 100',
    subtitle: 'Intense Brightening Mask',
    price: 950,
    originalPrice: 1100,
    rating: 4.8,
    reviewsCount: 410,
    category: 'Face Mask',
    skinTypes: ['All'],
    skinConcerns: ['Glow & Dullness', 'Blemishes & Texture'],
    routine: 'AM/PM',
    volume: '7 Sheets',
    badges: ['Brightening'],
    image: 'https://m.media-amazon.com/images/I/41k5P5uK+ZL._SX300_SY300_QL70_FMwebp_.jpg',
    accentColor: '#fcd34d',
    bgGradient: 'from-yellow-50 to-yellow-100',
    keyActives: [
      { name: 'Glutathione', purpose: 'Potent antioxidant brightening' },
      { name: 'Vitamin C', purpose: 'Fades dark spots' }
    ],
    fullIngredients: 'Water, Dipropylene Glycol, Glycerin, Glutathione, Ascorbic Acid, Niacinamide...',
    description: 'A highly concentrated brightening mask featuring nano-encapsulated glutathione to tackle dullness and deliver a translucent, glowing complexion.',
    benefits: ['Instantly brightens', 'Fades hyperpigmentation', 'Provides antioxidant protection'],
    usageHowTo: 'Apply to clean skin for 3-10 minutes. Follow with moisturizer.',
    isNew: true,
    stock: 55
  },
  {
    id: 'honey-melty-hair-pack',
    title: '&honey Melty Moist Repair Hair Pack Step 1.5',
    subtitle: 'Intensive Honey Moisture for Wavy/Frizzy Hair',
    price: 1250,
    originalPrice: 1400,
    rating: 4.9,
    reviewsCount: 820,
    category: 'Hair Care',
    skinTypes: ['All'],
    skinConcerns: ['Hydration'],
    routine: 'PM',
    volume: '130g',
    badges: ['Hair Care', 'Bestseller'],
    image: 'https://m.media-amazon.com/images/I/31+j+bI6x1L._SX300_SY300_QL70_FMwebp_.jpg',
    accentColor: '#f9a8d4',
    bgGradient: 'from-pink-50 to-pink-100',
    keyActives: [
      { name: 'Manuka Honey', percentage: '60%', purpose: 'Deep hydration' },
      { name: 'Rose Honey', percentage: '20%', purpose: 'Smoothness and shine' },
      { name: 'Raw Honey', percentage: '20%', purpose: 'Moisture retention' }
    ],
    fullIngredients: 'Water, Cetearyl Alcohol, Dimethicone, Honey, Argania Spinosa Kernel Oil, Shea Butter...',
    description: 'Step 1.5 in the &honey routine. This intensive hair pack is designed specifically to tame wavy, frizzy hair using a unique 14% moisture level formula driven by three types of honey.',
    benefits: ['Controls frizz', 'Deeply moisturizes', 'Leaves hair silky and manageable'],
    usageHowTo: 'Apply after shampooing and before conditioning. Leave on for 1 minute, then rinse or apply conditioner directly on top before rinsing both.',
    isBestSeller: true,
    stock: 75
  },
  {
    id: 'daiso-toilet-stamp',
    title: 'Daiso Toilet Stamp Cleaner - Floral',
    subtitle: 'Continuous Cleaning Gel Stamps',
    price: 250,
    originalPrice: 300,
    rating: 4.5,
    reviewsCount: 120,
    category: 'Home & Living',
    skinTypes: ['All'],
    skinConcerns: [],
    routine: 'AM/PM',
    volume: '6 Doses',
    badges: ['Home', 'Value'],
    image: 'https://m.media-amazon.com/images/I/41-wX-5S0fL._SX300_SY300_QL70_FMwebp_.jpg',
    accentColor: '#f43f5e',
    bgGradient: 'from-rose-50 to-rose-100',
    keyActives: [
      { name: 'Cleaning Agents', purpose: 'Prevents stains' },
      { name: 'Floral Fragrance', purpose: 'Deodorizes' }
    ],
    fullIngredients: 'Surfactants, Fragrance, Colorants',
    description: 'A convenient gel stamp cleaner that adheres to the inside of the toilet bowl, providing continuous cleaning and a fresh floral scent with every flush. 1 dose lasts about 1 week.',
    benefits: ['Prevents dirt buildup', 'Deodorizes continuously', 'Easy to apply'],
    usageHowTo: 'Press the applicator against the inside of a clean toilet bowl to release one gel stamp. Flush normally.',
    stock: 200
  },
  {
    id: 'itoen-matcha-latte',
    title: 'Itoen Matcha Latte Powder',
    subtitle: 'Rich Uji Matcha with Milk',
    price: 850,
    originalPrice: 950,
    rating: 4.8,
    reviewsCount: 230,
    category: 'Food & Drink',
    skinTypes: ['All'],
    skinConcerns: [],
    routine: 'AM/PM',
    volume: '180g',
    badges: ['Authentic Japanese', 'Drink'],
    image: 'https://m.media-amazon.com/images/I/51r2zZ8o+jL._SX300_SY300_QL70_FMwebp_.jpg',
    accentColor: '#15803d',
    bgGradient: 'from-green-50 to-green-100',
    keyActives: [
      { name: 'Uji Matcha', purpose: 'Authentic flavor and antioxidants' }
    ],
    fullIngredients: 'Sugar, Creaming Powder, Green Tea (Matcha), Skim Milk Powder, Salt...',
    description: 'A deliciously rich and creamy matcha latte powder made with high-quality Uji matcha from Kyoto. Easily dissolves in hot or cold water/milk.',
    benefits: ['Authentic cafe taste at home', 'Rich in antioxidants', 'Easy to prepare'],
    usageHowTo: 'Mix 3 teaspoons (15g) with 120ml of hot water or milk. Stir well.',
    stock: 90
  },
  {
    id: 'tsujiri-matcha-milk',
    title: 'Tsujiri Matcha Milk',
    subtitle: 'Premium Kyoto Uji Matcha Blend',
    price: 950,
    originalPrice: 1100,
    rating: 4.9,
    reviewsCount: 345,
    category: 'Food & Drink',
    skinTypes: ['All'],
    skinConcerns: [],
    routine: 'AM/PM',
    volume: '200g',
    badges: ['Bestseller', 'Premium'],
    image: 'https://m.media-amazon.com/images/I/41yXG16+e-L._SX300_SY300_QL70_FMwebp_.jpg', // Needs correct image
    accentColor: '#166534',
    bgGradient: 'from-green-50 to-green-100',
    keyActives: [
      { name: 'Tsujiri Premium Matcha', purpose: 'Deep, rich tea flavor' }
    ],
    fullIngredients: 'Sugar, Dextrin, Matcha, Vegetable Oil, Skim Milk Powder...',
    description: 'Experience the heritage of Tsujiri, a renowned Kyoto tea house established in 1860. This premium matcha milk powder offers a perfectly balanced, mellow flavor.',
    benefits: ['Heritage brand quality', 'Perfect balance of sweet and bitter', 'Dissolves easily'],
    usageHowTo: 'Mix 3 heaped teaspoons (17g) with 140ml of hot water or hot milk. Add ice for a cold drink.',
    isBestSeller: true,
    stock: 150
  }
];
`;

fs.writeFileSync('src/data/products.ts', code);
console.log('Updated src/data/products.ts with new crisp catalog');
